name: Deploy Book
on:
  - push
  - pull_request
  - release

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup default stable
    - name: Install mdBook
      run: cargo install mdbook@0.4.40
    - name: Prepare book
      working-directory: guide
      run: |
        rustc prepare-specs.rs
        ./prepare-specs
        mdbook build
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./guide/book

  deploy:
    needs: build

    if: "github.event_name == 'release' || github.event.ref == 'refs/heads/test-deploy'"

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
